export enum PaymentType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  ONE_TIME = 'ONE_TIME',
  LEAD_PURCHASE = 'LEAD_PURCHASE',
  COMMISSION = 'COMMISSION',
  SETUP_FEE = 'SETUP_FEE',
  REFUND = 'REFUND'
}