export const COMPANY_ERRORS = {
  NOT_FOUND: 'COMPANY_NOT_FOUND',
  BRANDING_NOT_FOUND: 'COMPANY_BRANDING_NOT_FOUND',
  USER_ALREADY_MEMBER: 'USER_ALREADY_COMPANY_MEMBER',
};

export const COMPANY_SUCCESS = {
  CREATED: 'COMPANY_SUCCESSFULLY_CREATED',
  UPDATED: 'COMPANY_SUCCESSFULLY_UPDATED',
  DELETED: 'COMPANY_SUCCESSFULLY_DELETED',
  BRANDING_UPDATED: 'COMPANY_BRANDING_SUCCESSFULLY_UPDATED',
};

export const DEFAULT_COMPANY_SETTINGS = {
  theme: 'light',
  notifications: true,
  language: 'en',
};