export enum BudgetCategory {
  LABOR = 'LABOR',
  MATERIALS = 'MATERIALS',
  EQUIPMENT = 'EQUIPMENT',
  SUBCONTRACTOR = 'SUBCONTRACTOR',
  PERMITS = 'PERMITS',
  UTILITIES = 'UTILITIES',
  TRAVEL = 'TRAVEL',
  OVERHEAD = 'OVERHEAD',
  CONTINGENCY = 'CONTINGENCY',
  OTHER = 'OTHER'
}
